### ISSUE TITLE
Chunked upload_documents

### ISSUE THREAD

**Issue by mrwunderbar666** [ccs-amsterdam/amcat4apiclient#2]
Extend `upload_documents` to allow for chunked uploads of documents (steal from `copy_index.py`). Add a progress bar for **large** uploads and maybe add some some documentation so the user knows right away what the server expects

**Comment by JBGruber** [comment]
Implemented in https://github.com/ccs-amsterdam/amcat4apiclient/commit/33b3014a44b108c514f27ac98a393244e832caec. Thanks @mrwunderbar666
